### ISSUE TITLE
cannot cythonize cutils.pyx

### ISSUE THREAD

**Issue by jcldc** [thomasorb/orb#15]
I have many problems to install orb package.

Mainly when I try to cythonize cutils.pyx file. (I tried different python interpreter, from 3.6 to 3.11)

First I had to modify cutils.pyx file at line 1723, because of a print statement which does not follow python3 syntax.

Once fixed, I have got these errors :
orb/cutils.pyx:2027:14: Cannot assign type 'double' to 'int'
orb/cutils.pyx:2028:14: Cannot assign type 'double' to 'int'

That I fixed by casting to  (int) the operation.

But again I get another cythonize error that I don't understand :
(see [cythonize_err.txt](https://github.com/user-attachments/files/15915960/cythonize_err.txt))

Thank you for your help
PS : 
- here is my cutils.pyx modification [cutils.pyx.txt](https://github.com/user-attachments/files/15916011/cutils.pyx.txt)

- here is the list of the python packages installed in my python environment [packages_installed.txt](https://github.com/user-attachments/files/15916090/packages_installed.txt)
- I am running Almalinux 8 (RedHat 8 like linux distrib)
- I have the same issue on ubuntu 22.04 (python 3.10.12)

**Comment by thomasorb** [comment]
I tried today using a freshly installed environment and everything works as expected. When I look at the versions of the packages you use I see that you did not follow the installation steps on the readme page (https://github.com/thomasorb/orb). You may want to first follow the indicated steps before attempting to compile the cython file. A complete environment file can be found [here](https://github.com/thomasorb/orb/blob/master/docs/orb3-env.txt)

You can then install a new environment with:
```bash
conda create -n orb3 --file orb3-env.txt
```

You can then compile the cython files with:
```bash
python setup.py build_ext --inplace
```
Hope this helps.

**Comment by jcldc** [comment]
Thanks for your reply.
The previous time, I was not using conda, but this time I followed carefully the installation steps on the readme page, using conda (btw : I have the latest conda version 24.4.0)  :
```
conda create -n orb3  -c conda-forge -c astropy -c anaconda python=3.10.8 numpy scipy matplotlib astropy cython h5py dill pandas pytables jupyterlab photutils astroquery reproject gitpython

conda activate orb3

pip install pyregion==2.1.1 --no-deps
pip install gvar==11.11.1 --no-deps
pip install lsqfit==13.0 --no-deps
pip install fpdf --no-deps
```

Here is the list of the  conda packages installed when I follow your readme  on the github page: 
[conda.list.txt](https://github.com/user-attachments/files/15932899/conda.list.txt)

And again, I got the same error during the cythonize build (see previous post) :
```
python setup.py build_ext --inplace
``` 
I guess that  is normal, because orb/cutils.pxd does not cythonize with cython above 0.29.X version and the version of cython installed by conda, when following your readme method, is version 3.0.10.

The question is why do we have a different list of packages installed when we follow the same installation method ?
 It may be due to the conda version (24.4.0 for me) ?
